server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html/static;
        index index.html;
        try_files $uri $uri/ @proxy_to_app;
    }

    location /css/ {
        alias /usr/share/nginx/html/public/css/;
        expires 30d;
    }

    location /js/ {
        alias /usr/share/nginx/html/public/javascript/;
        expires 30d;
    }

    location /img/ {
        alias /usr/share/nginx/html/public/image/;
        expires 30d;
    }

    location /api/ {
        proxy_pass http://fastapi:8000;
        proxy_set_header Host $host;
    }

    location @proxy_to_app {
        proxy_pass http://fastapi:8000;
        proxy_set_header Host $host;
    }
}